// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trace.Data;

#nullable disable

namespace Trace.Data.Migrations
{
    [DbContext(typeof(TraceDbContext))]
    [Migration("20260717125957_MoveVRefCruToClass")]
    partial class MoveVRefCruToClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trace.Data.Entities.BarrelRadius", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionTaskId")
                        .HasColumnType("integer");

                    b.Property<double>("Handicap")
                        .HasColumnType("double precision");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision");

                    b.Property<int>("TurnpointIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionTaskId", "Handicap", "TurnpointIndex")
                        .IsUnique();

                    b.ToTable("BarrelRadii");
                });

            modelBuilder.Entity("Trace.Data.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Site")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("VRefCruKmh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique();

                    b.ToTable("CompetitionClasses");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionClassId")
                        .HasColumnType("integer");

                    b.Property<int>("GliderId")
                        .HasColumnType("integer");

                    b.Property<int?>("P2PilotId")
                        .HasColumnType("integer");

                    b.Property<int>("PilotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GliderId");

                    b.HasIndex("P2PilotId");

                    b.HasIndex("PilotId");

                    b.HasIndex("CompetitionClassId", "GliderId")
                        .IsUnique();

                    b.ToTable("CompetitionEntries");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CompetitionClassId")
                        .HasColumnType("integer");

                    b.Property<double?>("DRefKm")
                        .HasColumnType("double precision");

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("RefHandicap")
                        .HasColumnType("double precision");

                    b.Property<double?>("TRefSec")
                        .HasColumnType("double precision");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<double?>("WindDirDeg")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedKmh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionClassId");

                    b.HasIndex("DayId", "CompetitionClassId", "Active")
                        .IsUnique()
                        .HasFilter("\"Active\" = true");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Trace.Data.Entities.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "DayNo")
                        .IsUnique();

                    b.ToTable("Days");
                });

            modelBuilder.Entity("Trace.Data.Entities.DayEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompetitionTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<int>("GliderId")
                        .HasColumnType("integer");

                    b.Property<int>("PilotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionClassId");

                    b.HasIndex("CompetitionTaskId");

                    b.HasIndex("GliderId");

                    b.HasIndex("PilotId");

                    b.HasIndex("DayId", "CompetitionClassId", "GliderId")
                        .IsUnique();

                    b.ToTable("DayEntries");
                });

            modelBuilder.Entity("Trace.Data.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AirspaceChecked")
                        .HasColumnType("boolean");

                    b.Property<bool>("AirspaceValid")
                        .HasColumnType("boolean");

                    b.Property<int>("DayEntryId")
                        .HasColumnType("integer");

                    b.Property<double?>("Distance")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly?>("Finish")
                        .HasColumnType("time without time zone");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly?>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DayEntryId")
                        .IsUnique();

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Trace.Data.Entities.Glider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CompetitionClassId")
                        .HasColumnType("integer");

                    b.Property<double>("Handicap")
                        .HasColumnType("double precision");

                    b.Property<int?>("Icao")
                        .HasColumnType("integer");

                    b.Property<string>("Registration")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionClassId", "CompNo")
                        .IsUnique();

                    b.ToTable("Gliders");
                });

            modelBuilder.Entity("Trace.Data.Entities.IgcFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.ToTable("IgcFiles");
                });

            modelBuilder.Entity("Trace.Data.Entities.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GliderId")
                        .HasColumnType("integer");

                    b.Property<string>("LoggerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GliderId");

                    b.ToTable("Loggers");
                });

            modelBuilder.Entity("Trace.Data.Entities.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountNo")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("Trace.Data.Entities.Turnpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Angle1")
                        .HasColumnType("double precision");

                    b.Property<double>("Angle2")
                        .HasColumnType("double precision");

                    b.Property<int>("CompetitionTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("DirectionType")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCheckpoint")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLine")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Radius1")
                        .HasColumnType("double precision");

                    b.Property<double>("Radius2")
                        .HasColumnType("double precision");

                    b.Property<int>("Style")
                        .HasColumnType("integer");

                    b.Property<string>("Waypoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionTaskId", "Index")
                        .IsUnique();

                    b.ToTable("Turnpoints");
                });

            modelBuilder.Entity("Trace.Data.Entities.BarrelRadius", b =>
                {
                    b.HasOne("Trace.Data.Entities.CompetitionTask", "CompetitionTask")
                        .WithMany("BarrelRadii")
                        .HasForeignKey("CompetitionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionTask");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionClass", b =>
                {
                    b.HasOne("Trace.Data.Entities.Competition", "Competition")
                        .WithMany("Classes")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionEntry", b =>
                {
                    b.HasOne("Trace.Data.Entities.CompetitionClass", "CompetitionClass")
                        .WithMany("Entries")
                        .HasForeignKey("CompetitionClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trace.Data.Entities.Glider", "Glider")
                        .WithMany()
                        .HasForeignKey("GliderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trace.Data.Entities.Pilot", "P2Pilot")
                        .WithMany()
                        .HasForeignKey("P2PilotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trace.Data.Entities.Pilot", "Pilot")
                        .WithMany("Entries")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionClass");

                    b.Navigation("Glider");

                    b.Navigation("P2Pilot");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionTask", b =>
                {
                    b.HasOne("Trace.Data.Entities.CompetitionClass", "CompetitionClass")
                        .WithMany("Tasks")
                        .HasForeignKey("CompetitionClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trace.Data.Entities.Day", "Day")
                        .WithMany("Tasks")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionClass");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Trace.Data.Entities.Day", b =>
                {
                    b.HasOne("Trace.Data.Entities.Competition", "Competition")
                        .WithMany("Days")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Trace.Data.Entities.DayEntry", b =>
                {
                    b.HasOne("Trace.Data.Entities.CompetitionClass", "CompetitionClass")
                        .WithMany()
                        .HasForeignKey("CompetitionClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trace.Data.Entities.CompetitionTask", "CompetitionTask")
                        .WithMany()
                        .HasForeignKey("CompetitionTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Trace.Data.Entities.Day", "Day")
                        .WithMany("Entries")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trace.Data.Entities.Glider", "Glider")
                        .WithMany()
                        .HasForeignKey("GliderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trace.Data.Entities.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionClass");

                    b.Navigation("CompetitionTask");

                    b.Navigation("Day");

                    b.Navigation("Glider");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("Trace.Data.Entities.Flight", b =>
                {
                    b.HasOne("Trace.Data.Entities.DayEntry", "DayEntry")
                        .WithOne("Flight")
                        .HasForeignKey("Trace.Data.Entities.Flight", "DayEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayEntry");
                });

            modelBuilder.Entity("Trace.Data.Entities.Glider", b =>
                {
                    b.HasOne("Trace.Data.Entities.CompetitionClass", "CompetitionClass")
                        .WithMany("Gliders")
                        .HasForeignKey("CompetitionClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionClass");
                });

            modelBuilder.Entity("Trace.Data.Entities.IgcFile", b =>
                {
                    b.HasOne("Trace.Data.Entities.Flight", "Flight")
                        .WithOne("IgcFile")
                        .HasForeignKey("Trace.Data.Entities.IgcFile", "FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Trace.Data.Entities.Logger", b =>
                {
                    b.HasOne("Trace.Data.Entities.Glider", "Glider")
                        .WithMany("Loggers")
                        .HasForeignKey("GliderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Glider");
                });

            modelBuilder.Entity("Trace.Data.Entities.Turnpoint", b =>
                {
                    b.HasOne("Trace.Data.Entities.CompetitionTask", "CompetitionTask")
                        .WithMany("Turnpoints")
                        .HasForeignKey("CompetitionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionTask");
                });

            modelBuilder.Entity("Trace.Data.Entities.Competition", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Days");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionClass", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Gliders");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Trace.Data.Entities.CompetitionTask", b =>
                {
                    b.Navigation("BarrelRadii");

                    b.Navigation("Turnpoints");
                });

            modelBuilder.Entity("Trace.Data.Entities.Day", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Trace.Data.Entities.DayEntry", b =>
                {
                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Trace.Data.Entities.Flight", b =>
                {
                    b.Navigation("IgcFile");
                });

            modelBuilder.Entity("Trace.Data.Entities.Glider", b =>
                {
                    b.Navigation("Loggers");
                });

            modelBuilder.Entity("Trace.Data.Entities.Pilot", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
